import { AIService } from '../services/ai-service.js';
import { GitHubService } from '../services/github-service.js';
import { FileSystemService } from '../services/filesystem-service.js';
import { TemplateService } from '../services/template-service.js';
import { validateProjectInput } from '../schemas/project-input-schema.js';

/**
 * Project Scaffolding Agent
 * Generates complete project structures using templates (preferred) or AI (fallback)
 */
export class ProjectScaffoldingAgent {
  constructor(provider = 'github') {
    this.agentName = 'Project Scaffolding Agent';
    this.version = '2.0.0';
    this.provider = provider;
    this.aiService = new AIService(provider);
    this.templateService = new TemplateService();
    this.fileSystemService = new FileSystemService();
  }

  /**
   * Create and publish project to GitHub or create locally
   * @param {Object} projectInput - Project configuration
   * @returns {Promise<Object>} Result with repository URL or local path and files created
   */
  async createProject(projectInput) {
    try {
      // Validate input
      console.log('🔍 Validating project input...');
      const validatedInput = validateProjectInput(projectInput);

      // Determine creation mode
      const isGitHubMode = validatedInput.repositoryUrl && validatedInput.githubToken;

      console.log(`📍 Mode: ${isGitHubMode ? 'GitHub' : 'Local'}`);

      // Step 1: Check if we have a template for this technology
      const hasTemplate = this.templateService.hasTemplate(validatedInput.technology);
      console.log(`🎯 Generation strategy: ${hasTemplate ? 'Template-based (reliable)' : 'AI-based (flexible)'}`);

      let projectStructure;
      let dependencyConfig = null;
      
      if (hasTemplate) {
        // Use template-based generation (preferred)
        console.log('📋 Generating project from tested template...');
        const templateResult = await this.templateService.generateFromTemplate(validatedInput);
        
        // Generate additional tool configurations (Prettier, ESLint, etc.)
        console.log('🔧 Generating tool configurations...');
        const toolConfigs = await this.templateService.generateToolConfigurations(
          validatedInput.dependencies || [],
          this.aiService
        );

        projectStructure = {
          files: [
            ...templateResult.files.map(f => ({ path: f.path, content: f.content })),
            ...toolConfigs.map(c => ({ path: c.filename, content: c.content }))
          ],
          metadata: {
            framework: validatedInput.technology,
            frameworkVersion: templateResult.frameworkVersion,
            toolsVersions: templateResult.toolsVersions,
            generatedWith: 'template',
            configurations: toolConfigs.map(c => c.filename)
          }
        };

        // Build dependencyConfig from template result for reporting
        dependencyConfig = {
          compatibleVersions: templateResult.toolsVersions,
          configurations: toolConfigs,
          packageJsonScripts: this._extractScriptsFromTemplate(templateResult)
        };
      } else {
        // Fallback to AI-based generation
        console.log('🤖 No template available, using AI generation...');
        
        // Step 1: Analyze dependencies and generate compatible configurations
        let dependencyConfig = null;
        if (validatedInput.dependencies && validatedInput.dependencies.length > 0) {
          console.log('🔧 Analyzing dependencies and generating compatible configurations...');
          dependencyConfig = await this.aiService.analyzeDependencies(validatedInput);
          console.log(`✅ Generated ${dependencyConfig.configurations?.length || 0} configuration files`);
          console.log(`📦 Compatible versions:`, Object.keys(dependencyConfig.compatibleVersions || {}).join(', '));
        }

        // Step 2: Generate project structure using AI (with dependency configs if available)
        console.log('🤖 Generating project structure with AI...');
        projectStructure = await this.aiService.generateProjectStructure(validatedInput, dependencyConfig);
      }

      // Validate generated structure
      if (!projectStructure.files || !Array.isArray(projectStructure.files)) {
        throw new Error('Invalid project structure generated by AI');
      }

      console.log(`📁 Generated ${projectStructure.files.length} files`);

      // Step 3: Create project in GitHub or locally
      if (isGitHubMode) {
        return await this._createGitHubProject(validatedInput, projectStructure, dependencyConfig);
      } else {
        return await this._createLocalProject(validatedInput, projectStructure, dependencyConfig);
      }
    } catch (error) {
      console.error('❌ Error creating project:', error.message);
      return {
        success: false,
        error: error.message,
        metadata: {
          agent: this.agentName,
          version: this.version,
          failedAt: new Date().toISOString(),
        },
      };
    }
  }

  /**
   * Create project in GitHub
   * @private
   */
  async _createGitHubProject(validatedInput, projectStructure, dependencyConfig) {
    // Initialize GitHub service with provided token
    const githubService = new GitHubService(validatedInput.githubToken);

    // Parse repository URL
    const { owner, repo } = githubService.parseRepositoryUrl(validatedInput.repositoryUrl);

    // Check if repository exists
    console.log('🔍 Checking if repository exists...');
    const repoExists = await githubService.repositoryExists(owner, repo);

    if (!repoExists) {
      console.log(`📦 Creating new ${validatedInput.isPrivate ? 'private' : 'public'} repository...`);
      await githubService.createRepository({
        name: repo,
        description: validatedInput.description || `${validatedInput.front} project using ${validatedInput.technology} ${validatedInput.version}`,
        isPrivate: validatedInput.isPrivate,
      });
      
      // Wait a bit for repository to be fully available (especially for private repos)
      console.log('⏳ Waiting for repository to be ready...');
      await new Promise(resolve => setTimeout(resolve, 2000));
    }

    // Upload files to GitHub
    console.log('📤 Uploading files to GitHub...');
    await githubService.createFilesInBatch({
      owner,
      repo,
      files: projectStructure.files,
      message: `feat: initial project scaffolding

Generated by ${this.agentName} v${this.version}

Project Type: ${validatedInput.front}
Technology: ${validatedInput.technology} ${validatedInput.version}
Files Created: ${projectStructure.files.length}`,
      branch: 'main',
    });

    // Add topics to repository
    const topics = [
      validatedInput.technology.toLowerCase().replace(/\s+/g, '-'),
      validatedInput.front.toLowerCase(),
      'ai-generated',
      'scaffolding',
    ];

    console.log('🏷️  Adding topics to repository...');
    try {
      await githubService.addTopics(owner, repo, topics);
    } catch (error) {
      console.warn(`⚠️  Warning: Could not add topics: ${error.message}`);
      // Don't fail the entire process if topics fail
    }

    // Get final repository data
    const repoData = await githubService.getRepository(owner, repo);

    return {
      mode: 'github',
      repositoryUrl: repoData.html_url,
      cloneUrl: repoData.clone_url,
      filesCreated: projectStructure.files.length,
      files: projectStructure.files.map(f => f.path),
      structure: projectStructure.files.map(f => ({ path: f.path, type: 'file' })),
      ...(dependencyConfig && {
        dependencyConfig: {
          versionsUsed: dependencyConfig.compatibleVersions,
          configurationsGenerated: dependencyConfig.configurations.map(c => c.filename),
          scriptsAdded: Object.keys(dependencyConfig.packageJsonScripts),
        }
      }),
    };
  }

  /**
   * Create project locally
   * @private
   */
  async _createLocalProject(validatedInput, projectStructure, dependencyConfig) {
    // Check if directory is writable
    console.log('🔍 Checking local directory...');
    const dirCheck = await this.fileSystemService.checkDirectory(validatedInput.localPath);
    
    if (!dirCheck.exists) {
      console.log('📁 Creating base directory...');
      // The createProjectLocally method will create it with recursive: true
    } else if (!dirCheck.writable) {
      throw new Error(`Directory ${validatedInput.localPath} is not writable`);
    }

    // Create project locally
    console.log('💾 Creating project files locally...');
    const result = await this.fileSystemService.createProjectLocally({
      basePath: validatedInput.localPath,
      projectName: validatedInput.projectName,
      files: projectStructure.files,
    });

    console.log(`✅ Project created at: ${result.path}`);

    return {
      success: true,
      data: {
        mode: 'local',
        projectPath: result.path,
        filesCreated: result.filesCreated,
        files: projectStructure.files.map(f => f.path),
        structure: projectStructure.structure,
        ...(dependencyConfig && {
          dependencyConfiguration: {
            versionsUsed: dependencyConfig.compatibleVersions,
            configurationsGenerated: dependencyConfig.configurations.map(c => c.filename),
            scriptsAdded: Object.keys(dependencyConfig.packageJsonScripts),
          }
        }),
      },
      metadata: {
        agent: this.agentName,
        version: this.version,
        provider: this.provider,
        generatedAt: new Date().toISOString(),
        projectName: validatedInput.projectName,
        technology: `${validatedInput.technology} ${validatedInput.version}`,
        front: validatedInput.front,
        dependenciesAnalyzed: validatedInput.dependencies?.length || 0,
      },
    };
  }

  /**
   * Preview project structure without creating repository
   * @param {Object} projectInput - Project configuration (without githubToken and repositoryUrl)
   * @returns {Promise<Object>} Generated structure preview
   */
  async previewProject(projectInput) {
    try {
      console.log('🔍 Generating project preview...');

      const configToAnalyze = {
        ...projectInput,
        includeTests: projectInput.includeTests ?? true,
        includeCICD: projectInput.includeCICD ?? true,
        includeDocker: projectInput.includeDocker ?? false,
      };

      // Step 1: Analyze dependencies if provided
      let dependencyConfig = null;
      if (projectInput.dependencies && projectInput.dependencies.length > 0) {
        console.log('🔧 Analyzing dependencies...');
        dependencyConfig = await this.aiService.analyzeDependencies(configToAnalyze);
        console.log(`✅ Analyzed ${Object.keys(dependencyConfig.compatibleVersions || {}).length} dependencies`);
      }

      // Step 2: Generate project structure
      const projectStructure = await this.aiService.generateProjectStructure(configToAnalyze, dependencyConfig);

      return {
        success: true,
        data: {
          filesCount: projectStructure.files.length,
          files: projectStructure.files.map(f => ({
            path: f.path,
            size: f.content.length,
          })),
          structure: projectStructure.structure,
          ...(dependencyConfig && {
            dependencyConfiguration: {
              versionsUsed: dependencyConfig.compatibleVersions,
              configurationsGenerated: dependencyConfig.configurations.map(c => ({
                filename: c.filename,
                description: c.description,
              })),
              scriptsAdded: Object.keys(dependencyConfig.packageJsonScripts),
            }
          }),
        },
        metadata: {
          agent: this.agentName,
          version: this.version,
          provider: this.provider,
          generatedAt: new Date().toISOString(),
        },
      };
    } catch (error) {
      return {
        success: false,
        error: error.message,
        metadata: {
          agent: this.agentName,
          version: this.version,
          failedAt: new Date().toISOString(),
        },
      };
    }
  }

  /**
   * Extract scripts from template result for reporting
   */
  _extractScriptsFromTemplate(templateResult) {
    // Find package.json file
    const packageJsonFile = templateResult.files.find(f => f.path === 'package.json');
    if (packageJsonFile) {
      try {
        const packageJson = JSON.parse(packageJsonFile.content);
        return packageJson.scripts || {};
      } catch (_error) {
        console.warn('Could not parse package.json from template');
        return {};
      }
    }
    return {};
  }
}
